name: test
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - plyfile
  - python=3.8
  - pip=23.2.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - pip:
    - submodules/depth-diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/gaussian-norms
    - pytorch-msssim
    - Pillow  
    - tqdm
    - tensorboard
    - faiss-gpu
    - lpips
